builders:
  floor_riverpod_builder:
    import: 'package:floor_riverpod_generator/floor_riverpod_generator.dart'
    builder_factories: ['floorRiverpodProviderBuilder']
    build_extensions: {'.dart': ['floorRiverpod.g.part']}
    auto_apply: dependents
    build_to: cache
    applies_builders: ['source_gen|combining_builder']
